<a href="https://colab.research.google.com/github/piyushy1/DeepLearningNotes/blob/master/Note1_Numpy_Manipulations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Kryders Law** :  Kryder's Law is the assumption that disk drive density, also known as areal density, will double every thirteen months. The implication of Kryder's Law is that as areal density improves, storage will become cheaper

**Moore's law** is the observation that the number of transistors in a dense integrated circuit doubles about every two years. 

In [10]:
!pip install mxnet-cu101

     |████████████████████████████████| 710.5MB 21kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [0]:
from mxnet import np, npx
npx.set_np()

In [0]:
# Row vector
x = np.arange(12)
print(x)
# shape lenght of each axis, size total number of elements in array
x.shape, x.size

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


((12,), 12)

In [0]:
# reshape array
x = x.reshape(3,4) # same circular opertion x.reshape(-1,4), x.reshape(3,-1)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [0]:
np.empty((3,4)) # grabs chunk of memory

array([[8.4688284e-36, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00]])

In [0]:
np.zeros((2,3,4)) # tensoer with two matricses of 3,4 zero initilaisation

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [0]:
# above with intialisng with ones.
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [0]:
# random probabilistic valuses with normal guassian
# this type of operation helps in intialising random weight in neural nets
np.random.normal(0,1,size =(3,4)) # here 0 is mean and 1 is std. deviation

array([[-3.542058  , -1.0918891 , -0.9027689 , -4.7112594 ],
       [ 1.1587671 ,  1.0828804 , -3.712164  ,  5.357013  ],
       [-3.9537592 ,  2.5092688 , -0.41603842, -1.0975479 ]])

In [0]:
# to get the excat values
np.array([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]],[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]]).shape

(2, 3, 4)

In [0]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # The ** operator is exponentiation

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [0]:
# exponential value
np.exp(x)

array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03])

In [0]:
# concatenation of arrays across axis (x =0, x=1)
x = np.arange(12).reshape(3, 4)
y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([x, y], axis=0), np.concatenate([x, y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [0]:
# construct binary logical operations
x==y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [0]:
# sum of array
x.sum() # or np.sum(x)

array(66.)

**Broadcasting Mechanism** when the shapes are not same.


In [0]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

# elementw wise add and final matrix will be of 3*2
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

**Indiexing and SLicing**  Index 0 is is the first element and [-1] last element 

In [0]:
x = np.arange(12).reshape(3, 4)
print(x,x[-1],x[1:3])

# write at specfic position
x[2,3] = 400
print(x)

# access rows and columns
x[1:3, 1:2]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] [ 8.  9. 10. 11.] [[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8.   9.  10. 400.]]


array([[5.],
       [9.]])

**[Saving Memory]** to find the memory allocation

In [0]:
m = np.arange(12).reshape(3, 4)
n = np.arange(12).reshape(3, 4)
before = id(m)
m = m+n

print(id(m) == before)

# in mxnet its
z = np.zeros_like(m)
print('id(z):', id(z))
z[:] = m + n
print('id(z):', id(z))

# or m+ = n can also be used to save memory 


False
id(z): 140065512558024
id(z): 140065512558024


**Data Preprocessing: A small play with Pandas**

In [0]:
import os

# Saved in the d2l package for later use
def mkdir_if_not_exist(path):
  if not isinstance(path, str):   #he isinstance() function returns True if the specified object is of the specified type, otherwise False.
    path = os.path.join(*path)
  if not os.path.exists(path):
    os.makedirs(path)

In [0]:
# create a random data in csv file
data_file = '../data/house_tiny.csv'
mkdir_if_not_exist('../data')
with open(data_file, 'w') as f:
  f.write('NumRooms,Alley,Price\n') # Column names
  f.write('NA,Pave,127500\n') # Each row is a data point
  f.write('2,NA,106000\n')
  f.write('4,NA,178100\n')
  f.write('NA,NA,140000\n')

In [5]:
# read data
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


**Handling Missing Data in Pandas** # use integerlocation (iloc) and fillna function

In [7]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs, outputs)

inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       NaN  Pave
1       2.0   NaN
2       4.0   NaN
3       NaN   NaN 0    127500
1    106000
2    178100
3    140000
Name: Price, dtype: int64
   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [8]:
# pandas treat Nan as categogricl value and can automatically crete dummy colum
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [11]:
# since now all the values have been converted to numerical so now we can convert them to nd array
from mxnet import np
X, y = np.array(inputs.values), np.array(outputs.values)
X, y

(array([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=float64),
 array([127500, 106000, 178100, 140000], dtype=int64))