<a href="https://colab.research.google.com/github/piyushy1/DeepLearningNotes/blob/master/Notes_2_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mxnet-cu101

     |████████████████████████████████| 710.5MB 27kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


**Scalar:** we call values consisting of just one numerical quantity scalars
x ∈ ℝ is a formal way to say that x is a real-valued scalar.


In [2]:
from mxnet import np, npx
npx.set_np()
x = np.array(3.0)
y = np.array(2.0)
x + y, x * y, x / y, x ** y

(array(5.), array(6.), array(1.5), array(9.))

**Vectors**: are array of number. are represetned by by bold face like **x,y,z** while sclars as *x,y,z*. So **x** = [*x1, x2, x3*] where *xi* is a scalar

In [3]:
# one d array vector 
x = np.arange(4)
x

array([0., 1., 2., 3.])

**DImensions**: like array vectors have length. SO vector x
consists of n real-valued scalars, we can express this as **x** ∈ ℝ^n

In [4]:
len(x), x.shape

(4, (4,))

**Matrices:** generalize vector from order 1 to 2. **A** ∈ ℝ^m*n. aij , to refer
to [A]ij .commas are inserted to separate indices only when necessary,
such as
and 
a2,3j
[
A]2i-1,3

**Tensors**: Vectors, for example, are first-order tensors, and matrices are second-order tensors. Tensors are denoted with capital letters of a special font face (e.g., X, Y, and Z) and their indexing
mechanism (e.g., xijk and [X]1,2i-1,3) is similar to that of matrices.

In [13]:
A = np.arange(20).reshape(5, 4)
print(A)
print('#################')

# to transpose
print(A.T)
print('#################')

# tensors
X = np.arange(24).reshape(2, 3, 4)
print(X)

print('#################')

# tensor airthmentic
A = np.arange(20).reshape(5, 4)
B = A.copy() # Assign a copy of A to B by allocating new memory
print(A, A + B)

print('#################')
# element wise operation
A*B

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]]
#################
[[ 0.  4.  8. 12. 16.]
 [ 1.  5.  9. 13. 17.]
 [ 2.  6. 10. 14. 18.]
 [ 3.  7. 11. 15. 19.]]
#################
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
#################
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]] [[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]
 [32. 34. 36. 38.]]
#################


array([[  0.,   1.,   4.,   9.],
       [ 16.,  25.,  36.,  49.],
       [ 64.,  81., 100., 121.],
       [144., 169., 196., 225.],
       [256., 289., 324., 361.]])

**Reduction and Non Reduction**

In [14]:
x = np.arange(4)
x, x.sum()

(array([0., 1., 2., 3.]), array(6.))

In [22]:
A.shape, A.sum()

# summation across rows and columns
Row = A.sum(axis=0)
Col = A.sum(axis=1)
print(Row, Col)

# Mean across rows
Mean_rows = A.mean(axis = 0)
Mean_cols = A.mean(axis = 1)

print(Mean_rows,Mean_cols)

# keep the dimesnion same
sum_A = A.sum(axis=1, keepdims=True)
sum_A 

[40. 45. 50. 55.] [ 6. 22. 38. 54. 70.]
[ 8.  9. 10. 11.] [ 1.5  5.5  9.5 13.5 17.5]


array([[ 6.],
       [22.],
       [38.],
       [54.],
       [70.]])